### ISSUE TITLE
Increase body buffer size

### ISSUE THREAD

**Issue by axelssonHakan** [qlik-oss/core-assisted-prescription-gateway#129]
A warn is logged then openresty (nginx) is using disc for buffer:
`a client request body is buffered to a temporary file /usr/local/openresty/nginx/client_body_temp/0000000001`

http://nginx.org/en/docs/http/ngx_http_core_module.html#client_body_buffer_size

**Comment by peol** [comment]
Fixed for most cases, the only log I see of this now is when admins go into Kibana UI which has a huge JavaScript file but I don't think we should optimize for that use case.
